apiVersion: v1
kind: Service
metadata:
  name: frontend-http
  labels:
    app: cms
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    name: frontend-http
  selector:
    app: cms
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-https
  labels:
    app: cms
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 443
    targetPort: 3443
    name: frontend-https
  selector:
    app: cms
    tier: frontend