apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cms
        tier: frontend
        restartFlag: node
    spec:
      containers:
      - name: frontend
        image: startingdreams/cms:v0.1.1
        imagePullPolicy: IfNotPresent
        command: ["/entrypoints/entrypoint", "cms"]
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: env-config
              key: environment
        - name: FRONTEND_KEY
          valueFrom:
            secretKeyRef:
              name: frontend.ssl
              key: frontend.key.pem
        - name: FRONTEND_CERT
          valueFrom:
            secretKeyRef:
              name: frontend.ssl
              key: frontend.cert.pem
        ports:
        - containerPort: 3000
        - containerPort: 3443
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: site-volume
            mountPath: /usr/src/app
          - name: entrypoints
            mountPath: /entrypoints
          - name: package-json
            mountPath: /usr/src/app/package.json
      volumes:
        - name: site-volume
          hostPath:
            path: /home/core/shared/build
        - name: entrypoints
          hostPath:
            path: /home/core/shared/entrypoints
        - name: package-json
          hostPath:
            path: /home/core/shared/package.json